/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabibliotecario;


/**
 *
 * @author ruben
 */
public class AltaUsuario1 extends javax.swing.JPanel {

  /**
   * Creates new form altaUsuario
   */
  public AltaUsuario1() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jSeparator2 = new javax.swing.JSeparator();
    txtSearchbar = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jSeparator3 = new javax.swing.JSeparator();
    jLabel19 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jLabel7 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    lblTitle = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel17 = new javax.swing.JLabel();
    txtSearchbar1 = new javax.swing.JTextField();
    jButton2 = new javax.swing.JButton();
    jLabel12 = new javax.swing.JLabel();
    jSeparator5 = new javax.swing.JSeparator();
    txtSearchbar2 = new javax.swing.JTextField();
    jButton6 = new javax.swing.JButton();
    gestionUsuario1 = new javax.swing.JButton();
    jLabel29 = new javax.swing.JLabel();
    jSeparator6 = new javax.swing.JSeparator();
    gestionUsuario2 = new javax.swing.JButton();
    gestionUsuario3 = new javax.swing.JButton();
    jLabel16 = new javax.swing.JLabel();

    jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator2.setForeground(new java.awt.Color(51, 51, 51));

    txtSearchbar.setText("Búsqueda...");
    txtSearchbar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtSearchbarActionPerformed(evt);
      }
    });

    jButton1.setText("Ir");

    jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator3.setForeground(new java.awt.Color(51, 51, 51));

    jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/toolbar_home.png"))); // NOI18N

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/b1.png"))); // NOI18N
    jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

    jLabel2.setText("Facultad de Estadística e Informática, Universidad Veracruzana");
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

    lblTitle.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
    lblTitle.setForeground(new java.awt.Color(0, 0, 102));
    lblTitle.setText(" Sistema Bibliotecario \"BUAEEI\"");
    jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 58));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/uv1.png"))); // NOI18N
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 102, -1));

    jLabel6.setBackground(new java.awt.Color(204, 204, 204));
    jLabel6.setText("Nombre: Jonh Nieve Blanco");
    jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 450, 22));

    jLabel8.setBackground(new java.awt.Color(204, 204, 204));
    jLabel8.setText("Teléfono: 22-10-21-45-94");
    jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 209, 22));

    jLabel10.setBackground(new java.awt.Color(204, 204, 204));
    jLabel10.setText("CP: 910000");
    jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 220, 22));

    jLabel11.setBackground(new java.awt.Color(204, 204, 204));
    jLabel11.setText("Dirección: José Azueta #124");
    jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 209, 22));

    jLabel13.setBackground(new java.awt.Color(204, 204, 204));
    jLabel13.setText("Carrera: Ingeniería de Software");
    jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 220, 22));

    jLabel14.setBackground(new java.awt.Color(204, 204, 204));
    jLabel14.setText("Facultad: Estadística e Informática");
    jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 220, 22));

    jLabel15.setBackground(new java.awt.Color(204, 204, 204));
    jLabel15.setText("Telefono (opcional):");
    jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 150, 22));

    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/2-user_-_single_add-128.png"))); // NOI18N
    jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

    jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    jLabel17.setText("ID: zS1401643 ");
    jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

    txtSearchbar1.setText("22-33-44-55-33");
    txtSearchbar1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtSearchbar1ActionPerformed(evt);
      }
    });
    jPanel1.add(txtSearchbar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 189, -1));

    jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    jButton2.setText("Aceptar");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, -1));

    jLabel12.setBackground(new java.awt.Color(204, 204, 204));
    jLabel12.setText("Correo: nievejohn@aol.com");
    jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 209, 22));

    jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
    jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 104, 750, 10));

    txtSearchbar2.setText("Búsqueda...");
    txtSearchbar2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtSearchbar2ActionPerformed(evt);
      }
    });
    jPanel1.add(txtSearchbar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 189, -1));

    jButton6.setText("Ir");
    jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 53, -1));

    gestionUsuario1.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    gestionUsuario1.setText("Gestionar usuario");
    gestionUsuario1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gestionUsuario1ActionPerformed(evt);
      }
    });
    jPanel1.add(gestionUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, 26));

    jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/toolbar_home.png"))); // NOI18N
    jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, -1, 26));

    jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator6.setForeground(new java.awt.Color(51, 51, 51));
    jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 150, 750, 11));

    gestionUsuario2.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    gestionUsuario2.setText("Gestionar préstamo");
    gestionUsuario2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gestionUsuario2ActionPerformed(evt);
      }
    });
    jPanel1.add(gestionUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, 26));

    gestionUsuario3.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    gestionUsuario3.setText("Verificar adeudo");
    gestionUsuario3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gestionUsuario3ActionPerformed(evt);
      }
    });
    jPanel1.add(gestionUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, 26));

    jLabel16.setBackground(new java.awt.Color(204, 204, 204));
    jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel16.setText("Registrar Alta");
    jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jLabel16.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
    jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 220, 22));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void txtSearchbar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchbar1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtSearchbar1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton2ActionPerformed

  private void txtSearchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchbarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtSearchbarActionPerformed

  private void txtSearchbar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchbar2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtSearchbar2ActionPerformed

  private void gestionUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuario1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_gestionUsuario1ActionPerformed

  private void gestionUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuario2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_gestionUsuario2ActionPerformed

  private void gestionUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuario3ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_gestionUsuario3ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton gestionUsuario1;
  private javax.swing.JButton gestionUsuario2;
  private javax.swing.JButton gestionUsuario3;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton6;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel29;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JSeparator jSeparator3;
  private javax.swing.JSeparator jSeparator5;
  private javax.swing.JSeparator jSeparator6;
  private javax.swing.JLabel lblTitle;
  private javax.swing.JTextField txtSearchbar;
  private javax.swing.JTextField txtSearchbar1;
  private javax.swing.JTextField txtSearchbar2;
  // End of variables declaration//GEN-END:variables
}
