/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabibliotecario;

import conection.SQLMethods;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author ruben
 */
public class AltaUsuario extends javax.swing.JPanel {

  private Usuario usuario;
  String alta;

  /**
   * Creates new form altaUsuario
   */
  public AltaUsuario() {
    initComponents();
  }

  public AltaUsuario(Usuario usuario, String alta) {
    this.usuario = usuario;
    this.alta = alta;
    initComponents();
  }

  private boolean isValidText(JTextField field) {
    return !field.getText().equals("") && !field.getText().trim().isEmpty();
  }

  private boolean validateTexts() {
    boolean flag = isValidText(txtName);
    if (flag) {
      flag = isValidText(txtTel);
      if (flag) {
        isValidText(txtAddress);
        if (flag) {
          isValidText(txtMail);
        }
      }
    }
    flag = validatePass();
    return flag;
  }

  private boolean validatePass() {
    char pass[] = txtPass.getPassword();
    char pass2[] = txtPass2.getPassword();
    String s1 = new String(pass);
    String s2 = new String(pass2);
    if (s1.equals(s2)) {
      return true;
    } else {
      JOptionPane.showMessageDialog(null,
          "Las contraseñas no coinciden",
          "Error",
          JOptionPane.ERROR_MESSAGE);
      return false;
    }

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    icnBooks = new javax.swing.JLabel();
    lblFEI = new javax.swing.JLabel();
    lblTitle = new javax.swing.JLabel();
    icnUVLogo = new javax.swing.JLabel();
    lblNombre = new javax.swing.JLabel();
    lblTel = new javax.swing.JLabel();
    lblDireccion = new javax.swing.JLabel();
    icnUser = new javax.swing.JLabel();
    lblID = new javax.swing.JLabel();
    btnAccept = new javax.swing.JButton();
    lblMail = new javax.swing.JLabel();
    jSeparator5 = new javax.swing.JSeparator();
    txtSearchbar2 = new javax.swing.JTextField();
    btnSearch = new javax.swing.JButton();
    gestionUsuario1 = new javax.swing.JButton();
    jLabel29 = new javax.swing.JLabel();
    jSeparator6 = new javax.swing.JSeparator();
    gestionUsuario2 = new javax.swing.JButton();
    gestionUsuario3 = new javax.swing.JButton();
    lblSubTitle = new javax.swing.JLabel();
    txtMail = new javax.swing.JTextField();
    txtAddress = new javax.swing.JTextField();
    txtName = new javax.swing.JTextField();
    txtTel = new javax.swing.JTextField();
    lblPass = new javax.swing.JLabel();
    lblPass2 = new javax.swing.JLabel();
    txtPass2 = new javax.swing.JPasswordField();
    txtPass = new javax.swing.JPasswordField();
    btnCancel = new javax.swing.JButton();

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    icnBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1.png"))); // NOI18N
    jPanel1.add(icnBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

    lblFEI.setText("Facultad de Estadística e Informática, Universidad Veracruzana");
    jPanel1.add(lblFEI, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

    lblTitle.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
    lblTitle.setForeground(new java.awt.Color(0, 0, 102));
    lblTitle.setText(" Sistema Bibliotecario \"BUAEEI\"");
    jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 58));

    icnUVLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uv1.png"))); // NOI18N
    jPanel1.add(icnUVLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 102, -1));

    lblNombre.setBackground(new java.awt.Color(255, 255, 255));
    lblNombre.setText("Nombre: ");
    lblNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 130, 22));

    lblTel.setBackground(new java.awt.Color(204, 204, 204));
    lblTel.setText("Teléfono:");
    lblTel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(lblTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 130, 22));

    lblDireccion.setBackground(new java.awt.Color(204, 204, 204));
    lblDireccion.setText("Dirección:");
    lblDireccion.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 130, 22));

    icnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2-user_-_single_add-128.png"))); // NOI18N
    jPanel1.add(icnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

    lblID.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    lblID.setText("ID: zS1401643 ");
    lblID.setText("ID: " + alta);
    jPanel1.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, 20));

    btnAccept.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    btnAccept.setText("Aceptar");
    btnAccept.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAcceptActionPerformed(evt);
      }
    });
    jPanel1.add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, -1));

    lblMail.setBackground(new java.awt.Color(204, 204, 204));
    lblMail.setText("Correo:");
    lblMail.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(lblMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 130, 22));

    jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
    jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 104, 750, 10));

    txtSearchbar2.setText("Búsqueda...");
    txtSearchbar2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtSearchbar2ActionPerformed(evt);
      }
    });
    jPanel1.add(txtSearchbar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 189, -1));

    btnSearch.setText("Ir");
    btnSearch.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSearchActionPerformed(evt);
      }
    });
    jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 53, -1));

    gestionUsuario1.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    gestionUsuario1.setText("Gestionar usuario");
    gestionUsuario1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gestionUsuario1ActionPerformed(evt);
      }
    });
    jPanel1.add(gestionUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, 26));

    jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbar_home.png"))); // NOI18N
    jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        jLabel29MouseReleased(evt);
      }
    });
    jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, -1, 26));

    jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator6.setForeground(new java.awt.Color(51, 51, 51));
    jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 150, 750, 11));

    gestionUsuario2.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    gestionUsuario2.setText("Gestionar préstamo");
    gestionUsuario2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gestionUsuario2ActionPerformed(evt);
      }
    });
    jPanel1.add(gestionUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, 26));

    gestionUsuario3.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    gestionUsuario3.setText("Verificar adeudo");
    gestionUsuario3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gestionUsuario3ActionPerformed(evt);
      }
    });
    jPanel1.add(gestionUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, 26));

    lblSubTitle.setBackground(new java.awt.Color(204, 204, 204));
    lblSubTitle.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    lblSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblSubTitle.setText("Registrar Usuario");
    lblSubTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    lblSubTitle.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
    jPanel1.add(lblSubTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 220, 22));
    jPanel1.add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 300, -1));
    jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 300, -1));

    txtName.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtNameActionPerformed(evt);
      }
    });
    jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 300, -1));
    jPanel1.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 300, -1));

    lblPass.setBackground(new java.awt.Color(204, 204, 204));
    lblPass.setText("Contraseña:");
    lblPass.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 130, 22));

    lblPass2.setBackground(new java.awt.Color(204, 204, 204));
    lblPass2.setText("Confirmar Contraseña:");
    lblPass2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(lblPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 130, 22));
    jPanel1.add(txtPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 300, -1));

    txtPass.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtPassActionPerformed(evt);
      }
    });
    jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 300, -1));

    btnCancel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    btnCancel.setText("Cancelar");
    btnCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelActionPerformed(evt);
      }
    });
    jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, -1, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
    if (validateTexts()) {
      Usuario us = new Usuario();
      us.setId(alta);
      us.setName(txtName.getText());
      us.setTel(txtTel.getText());
      us.setDirec(txtAddress.getText());
      us.setCorreo(txtMail.getText());
      String pass = new String(txtPass.getPassword());
      SQLMethods sql = new SQLMethods();
      if (sql.agregarUsuario(us, pass)) {
        MenuUsuario mu = new MenuUsuario(usuario);
        PaneB.callNxtPane((JFrame) SwingUtilities.getWindowAncestor(this), mu);
      }
    }
    // TODO add your handling code here:
  }//GEN-LAST:event_btnAcceptActionPerformed

  private void txtSearchbar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchbar2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtSearchbar2ActionPerformed

  private void gestionUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuario1ActionPerformed
    MenuUsuario mu = new MenuUsuario(usuario);
    PaneB.callNxtPane((JFrame) SwingUtilities.getWindowAncestor(this), mu);    // TODO add your handling code here:
  }//GEN-LAST:event_gestionUsuario1ActionPerformed

  private void gestionUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuario2ActionPerformed
    RegistrarPrestamo rp = new RegistrarPrestamo(usuario);
    PaneB.callNxtPane((JFrame) SwingUtilities.getWindowAncestor(this), rp);    // TODO add your handling code here:
  }//GEN-LAST:event_gestionUsuario2ActionPerformed

  private void gestionUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuario3ActionPerformed
    JOptionPane.showMessageDialog(null,
        "Por Implementar",
        "Por Implementar",
        JOptionPane.ERROR_MESSAGE);    // TODO add your handling code here:
  }//GEN-LAST:event_gestionUsuario3ActionPerformed

  private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    JOptionPane.showMessageDialog(null,
        "Por Implementar",
        "Por Implementar",
        JOptionPane.ERROR_MESSAGE);    // TODO add your handling code here:
  }//GEN-LAST:event_btnSearchActionPerformed

  private void jLabel29MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseReleased
    MenuCirculacion mc = new MenuCirculacion(usuario);
    PaneB.callNxtPane((JFrame) SwingUtilities.getWindowAncestor(this), mc);     // TODO add your handling code here:
  }//GEN-LAST:event_jLabel29MouseReleased

  private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtNameActionPerformed

  private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtPassActionPerformed

  private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    MenuUsuario mu = new MenuUsuario(usuario);
    PaneB.callNxtPane((JFrame) SwingUtilities.getWindowAncestor(this), mu);
  }//GEN-LAST:event_btnCancelActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAccept;
  private javax.swing.JButton btnCancel;
  private javax.swing.JButton btnSearch;
  private javax.swing.JButton gestionUsuario1;
  private javax.swing.JButton gestionUsuario2;
  private javax.swing.JButton gestionUsuario3;
  private javax.swing.JLabel icnBooks;
  private javax.swing.JLabel icnUVLogo;
  private javax.swing.JLabel icnUser;
  private javax.swing.JLabel jLabel29;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JSeparator jSeparator5;
  private javax.swing.JSeparator jSeparator6;
  private javax.swing.JLabel lblDireccion;
  private javax.swing.JLabel lblFEI;
  private javax.swing.JLabel lblID;
  private javax.swing.JLabel lblMail;
  private javax.swing.JLabel lblNombre;
  private javax.swing.JLabel lblPass;
  private javax.swing.JLabel lblPass2;
  private javax.swing.JLabel lblSubTitle;
  private javax.swing.JLabel lblTel;
  private javax.swing.JLabel lblTitle;
  private javax.swing.JTextField txtAddress;
  private javax.swing.JTextField txtMail;
  private javax.swing.JTextField txtName;
  private javax.swing.JPasswordField txtPass;
  private javax.swing.JPasswordField txtPass2;
  private javax.swing.JTextField txtSearchbar2;
  private javax.swing.JTextField txtTel;
  // End of variables declaration//GEN-END:variables
}
