/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabibliotecario;

import javax.swing.JOptionPane;


/**
 *
 * @author ruben
 */
public class AltaUsuario extends javax.swing.JPanel {

  /**
   * Creates new form altaUsuario
   */
  public AltaUsuario() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    icnBooks = new javax.swing.JLabel();
    lblFEI = new javax.swing.JLabel();
    lblTitle = new javax.swing.JLabel();
    icnUVLogo = new javax.swing.JLabel();
    txtNombre = new javax.swing.JLabel();
    txtTel = new javax.swing.JLabel();
    txtCP = new javax.swing.JLabel();
    txtDireccion = new javax.swing.JLabel();
    txtCarrera = new javax.swing.JLabel();
    txtFacultad = new javax.swing.JLabel();
    lblTel2 = new javax.swing.JLabel();
    icnUser = new javax.swing.JLabel();
    lblID = new javax.swing.JLabel();
    txtTel2 = new javax.swing.JTextField();
    btnAccept = new javax.swing.JButton();
    txtMail = new javax.swing.JLabel();
    jSeparator5 = new javax.swing.JSeparator();
    txtSearchbar2 = new javax.swing.JTextField();
    btnSearch = new javax.swing.JButton();
    gestionUsuario1 = new javax.swing.JButton();
    jLabel29 = new javax.swing.JLabel();
    jSeparator6 = new javax.swing.JSeparator();
    gestionUsuario2 = new javax.swing.JButton();
    gestionUsuario3 = new javax.swing.JButton();
    lblSubTitle = new javax.swing.JLabel();

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    icnBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1.png"))); // NOI18N
    jPanel1.add(icnBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

    lblFEI.setText("Facultad de Estadística e Informática, Universidad Veracruzana");
    jPanel1.add(lblFEI, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

    lblTitle.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
    lblTitle.setForeground(new java.awt.Color(0, 0, 102));
    lblTitle.setText(" Sistema Bibliotecario \"BUAEEI\"");
    jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 58));

    icnUVLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uv1.png"))); // NOI18N
    jPanel1.add(icnUVLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 102, -1));

    txtNombre.setBackground(new java.awt.Color(204, 204, 204));
    txtNombre.setText("Nombre: Jonh Nieve Blanco");
    txtNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 450, 22));

    txtTel.setBackground(new java.awt.Color(204, 204, 204));
    txtTel.setText("Teléfono: 22-10-21-45-94");
    txtTel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 209, 22));

    txtCP.setBackground(new java.awt.Color(204, 204, 204));
    txtCP.setText("CP: 910000");
    txtCP.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(txtCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 220, 22));

    txtDireccion.setBackground(new java.awt.Color(204, 204, 204));
    txtDireccion.setText("Dirección: José Azueta #124");
    txtDireccion.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 209, 22));

    txtCarrera.setBackground(new java.awt.Color(204, 204, 204));
    txtCarrera.setText("Carrera: Ingeniería de Software");
    txtCarrera.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(txtCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 220, 22));

    txtFacultad.setBackground(new java.awt.Color(204, 204, 204));
    txtFacultad.setText("Facultad: Estadística e Informática");
    txtFacultad.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(txtFacultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 220, 22));

    lblTel2.setBackground(new java.awt.Color(204, 204, 204));
    lblTel2.setText("Telefono (opcional):");
    lblTel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(lblTel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 150, 22));

    icnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2-user_-_single_add-128.png"))); // NOI18N
    jPanel1.add(icnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

    lblID.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    lblID.setText("ID: zS1401643 ");
    jPanel1.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

    txtTel2.setText("22-33-44-55-33");
    txtTel2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtTel2ActionPerformed(evt);
      }
    });
    jPanel1.add(txtTel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 189, -1));

    btnAccept.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    btnAccept.setText("Aceptar");
    btnAccept.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAcceptActionPerformed(evt);
      }
    });
    jPanel1.add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, -1));

    txtMail.setBackground(new java.awt.Color(204, 204, 204));
    txtMail.setText("Correo: nievejohn@aol.com");
    txtMail.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 209, 22));

    jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
    jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 104, 750, 10));

    txtSearchbar2.setText("Búsqueda...");
    txtSearchbar2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtSearchbar2ActionPerformed(evt);
      }
    });
    jPanel1.add(txtSearchbar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 189, -1));

    btnSearch.setText("Ir");
    btnSearch.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSearchActionPerformed(evt);
      }
    });
    jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 53, -1));

    gestionUsuario1.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    gestionUsuario1.setText("Gestionar usuario");
    gestionUsuario1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gestionUsuario1ActionPerformed(evt);
      }
    });
    jPanel1.add(gestionUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, 26));

    jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbar_home.png"))); // NOI18N
    jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, -1, 26));

    jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator6.setForeground(new java.awt.Color(51, 51, 51));
    jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 150, 750, 11));

    gestionUsuario2.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    gestionUsuario2.setText("Gestionar préstamo");
    gestionUsuario2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gestionUsuario2ActionPerformed(evt);
      }
    });
    jPanel1.add(gestionUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, 26));

    gestionUsuario3.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    gestionUsuario3.setText("Verificar adeudo");
    gestionUsuario3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gestionUsuario3ActionPerformed(evt);
      }
    });
    jPanel1.add(gestionUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, 26));

    lblSubTitle.setBackground(new java.awt.Color(204, 204, 204));
    lblSubTitle.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    lblSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblSubTitle.setText("Registrar Usuario");
    lblSubTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    lblSubTitle.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
    jPanel1.add(lblSubTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 220, 22));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void txtTel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTel2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtTel2ActionPerformed

  private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnAcceptActionPerformed

  private void txtSearchbar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchbar2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtSearchbar2ActionPerformed

  private void gestionUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuario1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_gestionUsuario1ActionPerformed

  private void gestionUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuario2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_gestionUsuario2ActionPerformed

  private void gestionUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuario3ActionPerformed
    JOptionPane.showMessageDialog(null,
              "Por Implementar",
              "Por Implementar",
              JOptionPane.ERROR_MESSAGE);    // TODO add your handling code here:
  }//GEN-LAST:event_gestionUsuario3ActionPerformed

  private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    JOptionPane.showMessageDialog(null,
              "Por Implementar",
              "Por Implementar",
              JOptionPane.ERROR_MESSAGE);    // TODO add your handling code here:
  }//GEN-LAST:event_btnSearchActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAccept;
  private javax.swing.JButton btnSearch;
  private javax.swing.JButton gestionUsuario1;
  private javax.swing.JButton gestionUsuario2;
  private javax.swing.JButton gestionUsuario3;
  private javax.swing.JLabel icnBooks;
  private javax.swing.JLabel icnUVLogo;
  private javax.swing.JLabel icnUser;
  private javax.swing.JLabel jLabel29;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JSeparator jSeparator5;
  private javax.swing.JSeparator jSeparator6;
  private javax.swing.JLabel lblFEI;
  private javax.swing.JLabel lblID;
  private javax.swing.JLabel lblSubTitle;
  private javax.swing.JLabel lblTel2;
  private javax.swing.JLabel lblTitle;
  private javax.swing.JLabel txtCP;
  private javax.swing.JLabel txtCarrera;
  private javax.swing.JLabel txtDireccion;
  private javax.swing.JLabel txtFacultad;
  private javax.swing.JLabel txtMail;
  private javax.swing.JLabel txtNombre;
  private javax.swing.JTextField txtSearchbar2;
  private javax.swing.JLabel txtTel;
  private javax.swing.JTextField txtTel2;
  // End of variables declaration//GEN-END:variables
}
