/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabibliotecario;

import conection.Conexion;
import javax.swing.JOptionPane;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import conection.SQLMethods;

/**
 *
 * @author Vivie
 */
public class Login extends javax.swing.JFrame {

  /**
   * Creates new form Login
   */
  public Login() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jTextField1 = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jSeparator1 = new javax.swing.JSeparator();
    jDesktopPane1 = new javax.swing.JDesktopPane();
    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    txtSearchbar = new javax.swing.JTextField();
    lblTitle = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    txtUsuario = new javax.swing.JTextField();
    lblIDRqst = new javax.swing.JLabel();
    lblPassRqst = new javax.swing.JLabel();
    btnIngresar = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jSeparator2 = new javax.swing.JSeparator();
    jSeparator3 = new javax.swing.JSeparator();
    jLabel7 = new javax.swing.JLabel();
    txtPass = new javax.swing.JPasswordField();
    lblError = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();

    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    jTextField1.setText("Búsqueda ...");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 36, Short.MAX_VALUE)
    );

    jDesktopPane1.setLayout(null);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(255, 255, 255));

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel2.setText("Facultad de Estadística e Informática, Universidad Veracruzana");
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

    txtSearchbar.setText("Búsqueda...");
    txtSearchbar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtSearchbarActionPerformed(evt);
      }
    });
    jPanel1.add(txtSearchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 313, -1));

    lblTitle.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
    lblTitle.setForeground(new java.awt.Color(0, 0, 102));
    lblTitle.setText(" Sistema Bibliotecario \"BUAEEI\"");
    jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 12, -1, 58));

    jButton1.setText("Ir");
    jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 53, -1));

    txtUsuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtUsuarioActionPerformed(evt);
      }
    });
    jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 260, 160, -1));

    lblIDRqst.setText("Ingresar ID");
    jPanel1.add(lblIDRqst, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

    lblPassRqst.setText("Contraseña");
    jPanel1.add(lblPassRqst, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

    btnIngresar.setText("Ingresar");
    btnIngresar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnIngresarActionPerformed(evt);
      }
    });
    jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, -1, -1));

    jLabel5.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 13)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(51, 0, 102));
    jLabel5.setText("*Si desea recuperar su cuenta, preséntese en la biblioteca.");
    jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 586, -1, -1));

    jLabel6.setText("jLabel6");
    jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 586, -1, 0));
    jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 580, 301, -1));

    jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
    jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 766, -1));

    jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
    jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 766, -1));

    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/b1.png"))); // NOI18N
    jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));
    jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 340, 160, -1));

    lblError.setForeground(new java.awt.Color(255, 0, 0));
    lblError.setText("Usuario y/o contraseña incorrectos");
    jPanel1.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/uv1.png"))); // NOI18N
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 12, 104, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtUsuarioActionPerformed

  private void txtSearchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchbarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtSearchbarActionPerformed

  private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
    // TODO add your handling code here:    
    char pass[] = txtPass.getPassword();
    String password = new String(pass);
    SQLMethods sql = new SQLMethods();
    if (sql.validarIngreso(txtUsuario.getText(), password) == true) {
      this.dispose();
      //this.setVisible(false);
      JOptionPane.showMessageDialog(null, "Bienvenido " + txtUsuario.getText()
              + "\n has ingresado satisfactoriamente al sistema",
              "Biblioteca BUAEEI ", JOptionPane.INFORMATION_MESSAGE);
              System.out.println("entre");
    } else {
      JOptionPane.showMessageDialog(null,
              "Verifique que sus datos sean correctos",
              "Acceso denegado.",
              JOptionPane.ERROR_MESSAGE);
      lblError.setVisible(true);
    }
  }//GEN-LAST:event_btnIngresarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      new Login().setVisible(true);
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnIngresar;
  private javax.swing.JButton jButton1;
  private javax.swing.JDesktopPane jDesktopPane1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JSeparator jSeparator3;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JLabel lblError;
  private javax.swing.JLabel lblIDRqst;
  private javax.swing.JLabel lblPassRqst;
  private javax.swing.JLabel lblTitle;
  private javax.swing.JPasswordField txtPass;
  private javax.swing.JTextField txtSearchbar;
  public static javax.swing.JTextField txtUsuario;
  // End of variables declaration//GEN-END:variables

}
