/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabibliotecario;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;


/**
 *
 * @author ruben
 */
public class MenuCirculacion1 extends javax.swing.JPanel {
  /**
   * Creates new form menu_actor
   */
  public MenuCirculacion1() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel12 = new javax.swing.JLabel();
    icnBooks = new javax.swing.JLabel();
    lblFEI = new javax.swing.JLabel();
    lblTitle = new javax.swing.JLabel();
    icnUVLogo = new javax.swing.JLabel();
    lblNombre = new javax.swing.JLabel();
    lblTel = new javax.swing.JLabel();
    lblMail = new javax.swing.JLabel();
    lblAddress = new javax.swing.JLabel();
    txtName = new javax.swing.JLabel();
    txtMail = new javax.swing.JLabel();
    txtAddress = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel17 = new javax.swing.JLabel();
    jSeparator5 = new javax.swing.JSeparator();
    txtSearchbar2 = new javax.swing.JTextField();
    jButton6 = new javax.swing.JButton();
    btnGestionarUsuario = new javax.swing.JButton();
    jLabel29 = new javax.swing.JLabel();
    jSeparator6 = new javax.swing.JSeparator();
    btnGestionarPrestamo = new javax.swing.JButton();
    btnVerificarAdeudo = new javax.swing.JButton();

    jLabel12.setBackground(new java.awt.Color(204, 204, 204));
    jLabel12.setText("Jonh Snow");
    jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

    setBackground(new java.awt.Color(255, 255, 255));
    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    icnBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1.png"))); // NOI18N
    add(icnBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

    lblFEI.setText("Facultad de Estadística e Informática, Universidad Veracruzana");
    add(lblFEI, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

    lblTitle.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
    lblTitle.setForeground(new java.awt.Color(0, 0, 102));
    lblTitle.setText(" Sistema Bibliotecario \"BUAEEI\"");
    add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 58));

    icnUVLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uv1.png"))); // NOI18N
    add(icnUVLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 102, -1));

    lblNombre.setBackground(new java.awt.Color(204, 204, 204));
    lblNombre.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 13)); // NOI18N
    lblNombre.setText("Nombre: ");
    add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 70, 22));

    lblTel.setBackground(new java.awt.Color(204, 204, 204));
    lblTel.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 13)); // NOI18N
    lblTel.setText("Telefono:");
    add(lblTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 70, 22));

    lblMail.setBackground(new java.awt.Color(204, 204, 204));
    lblMail.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 13)); // NOI18N
    lblMail.setText("Correo: ");
    add(lblMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 70, 22));

    lblAddress.setBackground(new java.awt.Color(204, 204, 204));
    lblAddress.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 13)); // NOI18N
    lblAddress.setText("Dirección:");
    add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 70, 22));

    txtName.setBackground(new java.awt.Color(204, 204, 204));
    txtName.setText("Maria Rosa Lopez");
    txtName.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 160, 22));

    txtMail.setBackground(new java.awt.Color(204, 204, 204));
    txtMail.setText("lopezmr@gmail.com");
    txtMail.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 160, 22));

    txtAddress.setBackground(new java.awt.Color(204, 204, 204));
    txtAddress.setText("Av. Jose Azueta #123");
    txtAddress.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 160, 22));

    jLabel15.setBackground(new java.awt.Color(204, 204, 204));
    jLabel15.setText("22-88-54-45-34");
    jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 160, 22));

    jLabel16.setBackground(new java.awt.Color(204, 204, 204));
    jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel16.setText("Bibliotecario de circulación");
    jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jLabel16.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
    add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 220, 22));

    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/14-128.png"))); // NOI18N
    add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 120, 130));

    jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    jLabel17.setText("ID: zS1401643 ");
    add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

    jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
    add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 104, 750, 10));

    txtSearchbar2.setText("Búsqueda...");
    txtSearchbar2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtSearchbar2ActionPerformed(evt);
      }
    });
    add(txtSearchbar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 189, -1));

    jButton6.setText("Ir");
    add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 53, -1));

    btnGestionarUsuario.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    btnGestionarUsuario.setText("Gestionar usuario");
    btnGestionarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnGestionarUsuarioMouseClicked(evt);
      }
    });
    btnGestionarUsuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGestionarUsuarioActionPerformed(evt);
      }
    });
    add(btnGestionarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, 26));

    jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbar_home.png"))); // NOI18N
    add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, -1, 26));

    jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator6.setForeground(new java.awt.Color(51, 51, 51));
    add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 150, 750, 11));

    btnGestionarPrestamo.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    btnGestionarPrestamo.setText("Gestionar préstamo");
    btnGestionarPrestamo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGestionarPrestamoActionPerformed(evt);
      }
    });
    add(btnGestionarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, 26));

    btnVerificarAdeudo.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    btnVerificarAdeudo.setText("Verificar adeudo");
    btnVerificarAdeudo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnVerificarAdeudoActionPerformed(evt);
      }
    });
    add(btnVerificarAdeudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, 26));
  }// </editor-fold>//GEN-END:initComponents

  private void txtSearchbar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchbar2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtSearchbar2ActionPerformed

  private void btnGestionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarUsuarioActionPerformed
    // TODO add your handling code here:
    MenuUsuario1 mu = new MenuUsuario1();
    PaneB.callNxtPane((JFrame) SwingUtilities.getWindowAncestor(this), mu);
  }//GEN-LAST:event_btnGestionarUsuarioActionPerformed

  private void btnGestionarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarPrestamoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnGestionarPrestamoActionPerformed

  private void btnVerificarAdeudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarAdeudoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnVerificarAdeudoActionPerformed

  private void btnGestionarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarUsuarioMouseClicked

  }//GEN-LAST:event_btnGestionarUsuarioMouseClicked

    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MenuLogin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MenuLogin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MenuLogin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MenuLogin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      new MenuCirculacion1().setVisible(true);
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnGestionarPrestamo;
  public javax.swing.JButton btnGestionarUsuario;
  private javax.swing.JButton btnVerificarAdeudo;
  private javax.swing.JLabel icnBooks;
  private javax.swing.JLabel icnUVLogo;
  private javax.swing.JButton jButton6;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel29;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JSeparator jSeparator5;
  private javax.swing.JSeparator jSeparator6;
  private javax.swing.JLabel lblAddress;
  private javax.swing.JLabel lblFEI;
  private javax.swing.JLabel lblMail;
  private javax.swing.JLabel lblNombre;
  private javax.swing.JLabel lblTel;
  private javax.swing.JLabel lblTitle;
  private javax.swing.JLabel txtAddress;
  private javax.swing.JLabel txtMail;
  private javax.swing.JLabel txtName;
  private javax.swing.JTextField txtSearchbar2;
  // End of variables declaration//GEN-END:variables

  
  
}
