/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabibliotecario;

import conection.SQLMethods;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Vivie
 */
public class MenuUsuario extends javax.swing.JPanel {

  Usuario usuario;

  public Usuario getUsuario() {
    return usuario;
  }

  public void setUsuario(Usuario usuario) {
    this.usuario = usuario;
  }

  /**
   * Creates new form Modificar1
   */
  public MenuUsuario() {
    initComponents();
  }

  public MenuUsuario(Usuario usuario) {
    this.usuario = usuario;
    initComponents();
  }

  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      new MenuUsuario().setVisible(true);
    });
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel4 = new javax.swing.JPanel();
    jSeparator5 = new javax.swing.JSeparator();
    icnBooks = new javax.swing.JLabel();
    lblFEI = new javax.swing.JLabel();
    txtSearchbar2 = new javax.swing.JTextField();
    lblTitle1 = new javax.swing.JLabel();
    btnSearch = new javax.swing.JButton();
    icnUVLogo = new javax.swing.JLabel();
    btnGestionarUsuario = new javax.swing.JButton();
    btnHome = new javax.swing.JLabel();
    txtSearchID = new javax.swing.JTextField();
    jSeparator6 = new javax.swing.JSeparator();
    btnGestionarPrestamo = new javax.swing.JButton();
    btnVerificarAdeudo = new javax.swing.JButton();
    lblID = new javax.swing.JLabel();
    btnDarAlta = new javax.swing.JButton();
    btnModificarUsuario = new javax.swing.JButton();
    btnVerHistorial = new javax.swing.JButton();
    btnScan = new javax.swing.JButton();

    jPanel4.setBackground(new java.awt.Color(255, 255, 255));
    jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
    jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 104, 750, 10));

    icnBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1.png"))); // NOI18N
    jPanel4.add(icnBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

    lblFEI.setText("Facultad de Estadística e Informática, Universidad Veracruzana");
    jPanel4.add(lblFEI, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

    txtSearchbar2.setText("Búsqueda...");
    txtSearchbar2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtSearchbar2ActionPerformed(evt);
      }
    });
    jPanel4.add(txtSearchbar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 189, -1));

    lblTitle1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
    lblTitle1.setForeground(new java.awt.Color(0, 0, 102));
    lblTitle1.setText(" Sistema Bibliotecario \"BUAEEI\"");
    jPanel4.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 58));

    btnSearch.setText("Ir");
    btnSearch.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSearchActionPerformed(evt);
      }
    });
    jPanel4.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 53, -1));

    icnUVLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uv1.png"))); // NOI18N
    jPanel4.add(icnUVLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 102, -1));

    btnGestionarUsuario.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    btnGestionarUsuario.setText("Gestionar usuario");
    btnGestionarUsuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGestionarUsuarioActionPerformed(evt);
      }
    });
    jPanel4.add(btnGestionarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, 26));

    btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbar_home.png"))); // NOI18N
    btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        btnHomeMouseReleased(evt);
      }
    });
    jPanel4.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, -1, 26));

    txtSearchID.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtSearchIDActionPerformed(evt);
      }
    });
    jPanel4.add(txtSearchID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 192, -1));

    jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator6.setForeground(new java.awt.Color(51, 51, 51));
    jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 150, 750, 11));

    btnGestionarPrestamo.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    btnGestionarPrestamo.setText("Gestionar préstamo");
    btnGestionarPrestamo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGestionarPrestamoActionPerformed(evt);
      }
    });
    jPanel4.add(btnGestionarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, 26));

    btnVerificarAdeudo.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    btnVerificarAdeudo.setText("Verificar adeudo");
    btnVerificarAdeudo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnVerificarAdeudoActionPerformed(evt);
      }
    });
    jPanel4.add(btnVerificarAdeudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, 26));

    lblID.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 13)); // NOI18N
    lblID.setText("Ingresar ID");
    jPanel4.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

    btnDarAlta.setText("Dar de alta");
    btnDarAlta.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDarAltaActionPerformed(evt);
      }
    });
    jPanel4.add(btnDarAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, 30));

    btnModificarUsuario.setText("Modificar usuario");
    btnModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnModificarUsuarioActionPerformed(evt);
      }
    });
    jPanel4.add(btnModificarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, 30));

    btnVerHistorial.setText("Ver historial");
    btnVerHistorial.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnVerHistorialActionPerformed(evt);
      }
    });
    jPanel4.add(btnVerHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, 30));

    btnScan.setText("Scan");
    btnScan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnScanActionPerformed(evt);
      }
    });
    jPanel4.add(btnScan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 90, 40));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void txtSearchbar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchbar2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtSearchbar2ActionPerformed

  private void btnGestionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarUsuarioActionPerformed
    // TODO add your handling code here:
    MenuUsuario mu = new MenuUsuario();
    mu.setVisible(true);
  }//GEN-LAST:event_btnGestionarUsuarioActionPerformed

  private void txtSearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchIDActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtSearchIDActionPerformed

  private void btnGestionarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarPrestamoActionPerformed
    RegistrarPrestamo rp = new RegistrarPrestamo(usuario);
    PaneB.callNxtPane((JFrame) SwingUtilities.getWindowAncestor(this), rp);    // TODO add your handling code here:
  }//GEN-LAST:event_btnGestionarPrestamoActionPerformed

  private void btnVerificarAdeudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarAdeudoActionPerformed
    JOptionPane.showMessageDialog(null,
        "Por Implementar",
        "Por Implementar",
        JOptionPane.ERROR_MESSAGE);    // TODO add your handling code here:
  }//GEN-LAST:event_btnVerificarAdeudoActionPerformed

  private void btnDarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarAltaActionPerformed
    SQLMethods sql = new SQLMethods();
    Usuario user = sql.consultarUsuario(txtSearchID.getText());
    if ((!txtSearchID.getText().equals("")) && (user.getId() == null)) {
      AltaUsuario au = new AltaUsuario(usuario, txtSearchID.getText());
      PaneB.callNxtPane((JFrame) SwingUtilities.getWindowAncestor(this), au);
    } else if (!txtSearchID.getText().equals("")) {
      JOptionPane.showMessageDialog(null,
          "El usuario ya existe",
          "Error",
          JOptionPane.ERROR_MESSAGE);
    } else {
      JOptionPane.showMessageDialog(null,
          "El campo ID está vacío",
          "Error",
          JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_btnDarAltaActionPerformed

  private void btnModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUsuarioActionPerformed
    SQLMethods sql = new SQLMethods();
    Usuario user = sql.consultarUsuario(txtSearchID.getText());
    if ((!txtSearchID.getText().equals("")) && (user.getId() != null)) {
      ModificarUsuario mu = new ModificarUsuario(usuario, user);
      PaneB.callNxtPane((JFrame) SwingUtilities.getWindowAncestor(this), mu);
    } else if(!txtSearchID.getText().equals("")) {
      JOptionPane.showMessageDialog(null,
          "El usuario no existe",
          "Error",
          JOptionPane.ERROR_MESSAGE);
    } else {
      JOptionPane.showMessageDialog(null,
          "El campo ID está vacío",
          "Error",
          JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_btnModificarUsuarioActionPerformed

  private void btnVerHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHistorialActionPerformed
    JOptionPane.showMessageDialog(null,
        "Por Implementar",
        "Por Implementar",
        JOptionPane.ERROR_MESSAGE); // TODO add your handling code here:
  }//GEN-LAST:event_btnVerHistorialActionPerformed

  private void btnHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseReleased
    MenuCirculacion mc = new MenuCirculacion(usuario);
    PaneB.callNxtPane((JFrame) SwingUtilities.getWindowAncestor(this), mc);
  }//GEN-LAST:event_btnHomeMouseReleased

  private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    JOptionPane.showMessageDialog(null,
        "Por Implementar",
        "Por Implementar",
        JOptionPane.ERROR_MESSAGE);    // TODO add your handling code here:
  }//GEN-LAST:event_btnSearchActionPerformed

  private void btnScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScanActionPerformed
    JOptionPane.showMessageDialog(null,
        "Por Implementar",
        "Por Implementar",
        JOptionPane.ERROR_MESSAGE);
   }//GEN-LAST:event_btnScanActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnDarAlta;
  private javax.swing.JButton btnGestionarPrestamo;
  private javax.swing.JButton btnGestionarUsuario;
  private javax.swing.JLabel btnHome;
  private javax.swing.JButton btnModificarUsuario;
  private javax.swing.JButton btnScan;
  private javax.swing.JButton btnSearch;
  private javax.swing.JButton btnVerHistorial;
  private javax.swing.JButton btnVerificarAdeudo;
  private javax.swing.JLabel icnBooks;
  private javax.swing.JLabel icnUVLogo;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JSeparator jSeparator5;
  private javax.swing.JSeparator jSeparator6;
  private javax.swing.JLabel lblFEI;
  private javax.swing.JLabel lblID;
  private javax.swing.JLabel lblTitle1;
  private javax.swing.JTextField txtSearchID;
  private javax.swing.JTextField txtSearchbar2;
  // End of variables declaration//GEN-END:variables
}
