/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabibliotecario;
import conection.SQLMethods;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ruben
 */
public class menuCirculacion extends javax.swing.JPanel {

  /**
   * Creates new form menu_actor
   */
  public menuCirculacion() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel12 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    lblTitle = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel17 = new javax.swing.JLabel();
    jSeparator5 = new javax.swing.JSeparator();
    txtSearchbar2 = new javax.swing.JTextField();
    jButton6 = new javax.swing.JButton();
    gestionUsuario1 = new javax.swing.JButton();
    jLabel29 = new javax.swing.JLabel();
    jSeparator6 = new javax.swing.JSeparator();
    gestionUsuario2 = new javax.swing.JButton();
    gestionUsuario3 = new javax.swing.JButton();

    jLabel12.setBackground(new java.awt.Color(204, 204, 204));
    jLabel12.setText("Jonh Snow");
    jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

    setBackground(new java.awt.Color(255, 255, 255));
    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/b1.png"))); // NOI18N
    add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

    jLabel2.setText("Facultad de Estadística e Informática, Universidad Veracruzana");
    add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

    lblTitle.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
    lblTitle.setForeground(new java.awt.Color(0, 0, 102));
    lblTitle.setText(" Sistema Bibliotecario \"BUAEEI\"");
    add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 58));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/uv1.png"))); // NOI18N
    add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 102, -1));

    jLabel6.setBackground(new java.awt.Color(204, 204, 204));
    jLabel6.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 13)); // NOI18N
    jLabel6.setText("Nombre: ");
    add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 70, 22));

    jLabel8.setBackground(new java.awt.Color(204, 204, 204));
    jLabel8.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 13)); // NOI18N
    jLabel8.setText("Telefono:");
    add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 70, 22));

    jLabel10.setBackground(new java.awt.Color(204, 204, 204));
    jLabel10.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 13)); // NOI18N
    jLabel10.setText("Correo: ");
    add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 70, 22));

    jLabel11.setBackground(new java.awt.Color(204, 204, 204));
    jLabel11.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 13)); // NOI18N
    jLabel11.setText("Dirección:");
    add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 70, 22));

    jLabel9.setBackground(new java.awt.Color(204, 204, 204));
    jLabel9.setText("Maria Rosa Lopez");
    jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 160, 22));

    jLabel13.setBackground(new java.awt.Color(204, 204, 204));
    jLabel13.setText("lopezmr@gmail.com");
    jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 160, 22));

    jLabel14.setBackground(new java.awt.Color(204, 204, 204));
    jLabel14.setText("Av. Jose Azueta #123");
    jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 160, 22));

    jLabel15.setBackground(new java.awt.Color(204, 204, 204));
    jLabel15.setText("22-88-54-45-34");
    jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 160, 22));

    jLabel16.setBackground(new java.awt.Color(204, 204, 204));
    jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel16.setText("Bibliotecario de circulación");
    jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jLabel16.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
    add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 220, 22));

    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/14-128.png"))); // NOI18N
    add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

    jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    jLabel17.setText("ID: zS1401643 ");
    add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

    jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
    add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 104, 750, 10));

    txtSearchbar2.setText("Búsqueda...");
    txtSearchbar2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtSearchbar2ActionPerformed(evt);
      }
    });
    add(txtSearchbar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 189, -1));

    jButton6.setText("Ir");
    add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 53, -1));

    gestionUsuario1.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    gestionUsuario1.setText("Gestionar usuario");
    gestionUsuario1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gestionUsuario1ActionPerformed(evt);
      }
    });
    add(gestionUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, 26));

    jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/toolbar_home.png"))); // NOI18N
    add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, -1, 26));

    jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator6.setForeground(new java.awt.Color(51, 51, 51));
    add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 150, 750, 11));

    gestionUsuario2.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    gestionUsuario2.setText("Gestionar préstamo");
    gestionUsuario2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gestionUsuario2ActionPerformed(evt);
      }
    });
    add(gestionUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, 26));

    gestionUsuario3.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    gestionUsuario3.setText("Verificar adeudo");
    gestionUsuario3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gestionUsuario3ActionPerformed(evt);
      }
    });
    add(gestionUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, 26));
  }// </editor-fold>//GEN-END:initComponents

  private void txtSearchbar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchbar2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtSearchbar2ActionPerformed

  private void gestionUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuario1ActionPerformed
    // TODO add your handling code here:
    SQLMethods sql = new SQLMethods();
    menuUsuario mu = new menuUsuario();
     this.setContentPane(mu);
     this.invalidate();
     this.validate();
  }//GEN-LAST:event_gestionUsuario1ActionPerformed

  private void gestionUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuario2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_gestionUsuario2ActionPerformed

  private void gestionUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuario3ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_gestionUsuario3ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton gestionUsuario1;
  private javax.swing.JButton gestionUsuario2;
  private javax.swing.JButton gestionUsuario3;
  private javax.swing.JButton jButton6;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel29;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JSeparator jSeparator5;
  private javax.swing.JSeparator jSeparator6;
  private javax.swing.JLabel lblTitle;
  private javax.swing.JTextField txtSearchbar2;
  // End of variables declaration//GEN-END:variables
}
