/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabibliotecario;

/**
 *
 * @author ruben
 */
public class Modificar1 extends javax.swing.JPanel {

  /**
   * Creates new form Modificar1
   */
  public Modificar1() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel4 = new javax.swing.JPanel();
    jSeparator5 = new javax.swing.JSeparator();
    jLabel9 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    txtSearchbar2 = new javax.swing.JTextField();
    lblTitle1 = new javax.swing.JLabel();
    jButton6 = new javax.swing.JButton();
    jLabel16 = new javax.swing.JLabel();
    gestionUsuario1 = new javax.swing.JButton();
    jLabel19 = new javax.swing.JLabel();
    txtSearchbar6 = new javax.swing.JTextField();
    jSeparator6 = new javax.swing.JSeparator();
    gestionUsuario2 = new javax.swing.JButton();
    gestionUsuario3 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jButton9 = new javax.swing.JButton();
    jButton10 = new javax.swing.JButton();
    jButton11 = new javax.swing.JButton();

    jPanel4.setBackground(new java.awt.Color(255, 255, 255));
    jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
    jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 103, 811, 11));

    jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/b1.png"))); // NOI18N
    jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

    jLabel12.setText("Facultad de Estadística e Informática, Universidad Veracruzana");
    jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

    txtSearchbar2.setText("Búsqueda...");
    txtSearchbar2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtSearchbar2ActionPerformed(evt);
      }
    });
    jPanel4.add(txtSearchbar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 117, 189, -1));

    lblTitle1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
    lblTitle1.setForeground(new java.awt.Color(0, 0, 102));
    lblTitle1.setText(" Sistema Bibliotecario \"BUAEEI\"");
    jPanel4.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 58));

    jButton6.setText("Ir");
    jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 117, 53, -1));

    jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/uv1.png"))); // NOI18N
    jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 102, -1));

    gestionUsuario1.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    gestionUsuario1.setText("Gestionar usuario");
    gestionUsuario1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gestionUsuario1ActionPerformed(evt);
      }
    });
    jPanel4.add(gestionUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 118, -1, 26));

    jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/toolbar_home.png"))); // NOI18N
    jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 122, -1, 26));

    txtSearchbar6.setText("2255664433");
    txtSearchbar6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtSearchbar6ActionPerformed(evt);
      }
    });
    jPanel4.add(txtSearchbar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 257, 192, -1));

    jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator6.setForeground(new java.awt.Color(51, 51, 51));
    jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 150, 820, 11));

    gestionUsuario2.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    gestionUsuario2.setText("Gestionar préstamo");
    gestionUsuario2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gestionUsuario2ActionPerformed(evt);
      }
    });
    jPanel4.add(gestionUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 118, -1, 26));

    gestionUsuario3.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    gestionUsuario3.setText("Verificar adeudo");
    gestionUsuario3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gestionUsuario3ActionPerformed(evt);
      }
    });
    jPanel4.add(gestionUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 118, -1, 26));

    jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    jLabel1.setText("Ingresar ID");
    jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 235, -1, -1));

    jButton9.setText("Dar de alta");
    jButton9.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton9ActionPerformed(evt);
      }
    });
    jPanel4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, 30));

    jButton10.setText("Modificar usuario");
    jButton10.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton10ActionPerformed(evt);
      }
    });
    jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, 30));

    jButton11.setText("Ver historial");
    jButton11.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton11ActionPerformed(evt);
      }
    });
    jPanel4.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, -1, 30));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 818, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void txtSearchbar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchbar2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtSearchbar2ActionPerformed

  private void gestionUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuario1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_gestionUsuario1ActionPerformed

  private void txtSearchbar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchbar6ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtSearchbar6ActionPerformed

  private void gestionUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuario2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_gestionUsuario2ActionPerformed

  private void gestionUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuario3ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_gestionUsuario3ActionPerformed

  private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton9ActionPerformed

  private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton10ActionPerformed

  private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton11ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton gestionUsuario1;
  private javax.swing.JButton gestionUsuario2;
  private javax.swing.JButton gestionUsuario3;
  private javax.swing.JButton jButton10;
  private javax.swing.JButton jButton11;
  private javax.swing.JButton jButton6;
  private javax.swing.JButton jButton9;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JSeparator jSeparator5;
  private javax.swing.JSeparator jSeparator6;
  private javax.swing.JLabel lblTitle1;
  private javax.swing.JTextField txtSearchbar2;
  private javax.swing.JTextField txtSearchbar6;
  // End of variables declaration//GEN-END:variables
}
