/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabibliotecario;

/**
 *
 * @author Vivie
 */
public class registrarRenovacion extends javax.swing.JPanel {

  /**
   * Creates new form registrarRenovacion
   */
  public registrarRenovacion() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel4 = new javax.swing.JPanel();
    jSeparator5 = new javax.swing.JSeparator();
    jLabel9 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    txtSearchbar2 = new javax.swing.JTextField();
    lblTitle1 = new javax.swing.JLabel();
    jButton6 = new javax.swing.JButton();
    jLabel16 = new javax.swing.JLabel();
    btnGestionarUsuario = new javax.swing.JButton();
    jLabel19 = new javax.swing.JLabel();
    txtSearchbar6 = new javax.swing.JTextField();
    jSeparator6 = new javax.swing.JSeparator();
    btnGestionarPrestamo = new javax.swing.JButton();
    btnVerificarAdeudo = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    btnAceptar = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    txtSearchbar7 = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();

    jPanel4.setBackground(new java.awt.Color(255, 255, 255));
    jPanel4.setPreferredSize(new java.awt.Dimension(750, 700));
    jPanel4.setRequestFocusEnabled(false);
    jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
    jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 103, 811, 11));

    jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/b1.png"))); // NOI18N
    jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

    jLabel12.setText("Facultad de Estadística e Informática, Universidad Veracruzana");
    jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

    txtSearchbar2.setText("Búsqueda...");
    txtSearchbar2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtSearchbar2ActionPerformed(evt);
      }
    });
    jPanel4.add(txtSearchbar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 117, 189, -1));

    lblTitle1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
    lblTitle1.setForeground(new java.awt.Color(0, 0, 102));
    lblTitle1.setText(" Sistema Bibliotecario \"BUAEEI\"");
    jPanel4.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 58));

    jButton6.setText("Ir");
    jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 117, 53, -1));

    jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/uv1.png"))); // NOI18N
    jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 102, -1));

    btnGestionarUsuario.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    btnGestionarUsuario.setText("Gestionar usuario");
    btnGestionarUsuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGestionarUsuarioActionPerformed(evt);
      }
    });
    jPanel4.add(btnGestionarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, 26));

    jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/toolbar_home.png"))); // NOI18N
    jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 122, -1, 26));

    txtSearchbar6.setText("zS14011643");
    txtSearchbar6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtSearchbar6ActionPerformed(evt);
      }
    });
    jPanel4.add(txtSearchbar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 192, -1));

    jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator6.setForeground(new java.awt.Color(51, 51, 51));
    jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 150, 820, 11));

    btnGestionarPrestamo.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    btnGestionarPrestamo.setText("Gestionar préstamo");
    btnGestionarPrestamo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGestionarPrestamoActionPerformed(evt);
      }
    });
    jPanel4.add(btnGestionarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, 26));

    btnVerificarAdeudo.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    btnVerificarAdeudo.setText("Verificar adeudo");
    btnVerificarAdeudo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnVerificarAdeudoActionPerformed(evt);
      }
    });
    jPanel4.add(btnVerificarAdeudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, 26));

    jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(102, 0, 0));
    jLabel1.setText("Estado: prestado");
    jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, -1));

    btnAceptar.setText("Aceptar");
    btnAceptar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAceptarActionPerformed(evt);
      }
    });
    jPanel4.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, 30));

    jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    jLabel2.setText("Escanee el código del material ó ingrese el número de folio:");
    jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

    txtSearchbar7.setText("111222323123");
    txtSearchbar7.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtSearchbar7ActionPerformed(evt);
      }
    });
    jPanel4.add(txtSearchbar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 192, -1));

    jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    jLabel3.setText("Ingrese ID del usuario lector:");
    jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 20));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void txtSearchbar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchbar2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtSearchbar2ActionPerformed

  private void btnGestionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarUsuarioActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnGestionarUsuarioActionPerformed

  private void txtSearchbar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchbar6ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtSearchbar6ActionPerformed

  private void btnGestionarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarPrestamoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnGestionarPrestamoActionPerformed

  private void btnVerificarAdeudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarAdeudoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnVerificarAdeudoActionPerformed

  private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnAceptarActionPerformed

  private void txtSearchbar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchbar7ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtSearchbar7ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAceptar;
  private javax.swing.JButton btnGestionarPrestamo;
  private javax.swing.JButton btnGestionarUsuario;
  private javax.swing.JButton btnVerificarAdeudo;
  private javax.swing.JButton jButton6;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JSeparator jSeparator5;
  private javax.swing.JSeparator jSeparator6;
  private javax.swing.JLabel lblTitle1;
  private javax.swing.JTextField txtSearchbar2;
  private javax.swing.JTextField txtSearchbar6;
  private javax.swing.JTextField txtSearchbar7;
  // End of variables declaration//GEN-END:variables
}
