/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabibliotecario;

/**
 *
 * @author Vivie
 */
public class RegistrarPrestamo2 extends javax.swing.JPanel {

  /**
   * Creates new form registrarPrestamo2
   */
  public RegistrarPrestamo2() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel7 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    lblTitle = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel17 = new javax.swing.JLabel();
    txtSearchbar1 = new javax.swing.JTextField();
    jButton2 = new javax.swing.JButton();
    jLabel12 = new javax.swing.JLabel();
    jSeparator4 = new javax.swing.JSeparator();
    txtSearchbar2 = new javax.swing.JTextField();
    jButton3 = new javax.swing.JButton();
    jSeparator5 = new javax.swing.JSeparator();
    gestionUsuario2 = new javax.swing.JButton();
    gestionUsuario1 = new javax.swing.JButton();
    gestionUsuario3 = new javax.swing.JButton();
    jLabel20 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jLabel9 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    lblTitle1 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    jLabel18 = new javax.swing.JLabel();
    jLabel19 = new javax.swing.JLabel();
    jLabel21 = new javax.swing.JLabel();
    jLabel22 = new javax.swing.JLabel();
    jLabel23 = new javax.swing.JLabel();
    jLabel24 = new javax.swing.JLabel();
    btnAceptar = new javax.swing.JButton();
    jLabel27 = new javax.swing.JLabel();
    jSeparator6 = new javax.swing.JSeparator();
    txtSearchbar4 = new javax.swing.JTextField();
    jButton5 = new javax.swing.JButton();
    jSeparator7 = new javax.swing.JSeparator();
    btnGestionarPrestamo = new javax.swing.JButton();
    btnGestionarUsuario = new javax.swing.JButton();
    gestionUsuario6 = new javax.swing.JButton();
    jLabel28 = new javax.swing.JLabel();
    jComboBox1 = new javax.swing.JComboBox<>();

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/b1.png"))); // NOI18N
    jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

    jLabel2.setText("Facultad de Estadística e Informática, Universidad Veracruzana");
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

    lblTitle.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
    lblTitle.setForeground(new java.awt.Color(0, 0, 102));
    lblTitle.setText(" Sistema Bibliotecario \"BUAEEI\"");
    jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 58));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/uv1.png"))); // NOI18N
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 102, -1));

    jLabel6.setBackground(new java.awt.Color(204, 204, 204));
    jLabel6.setText("Nombre: Jonh Nieve Blanco");
    jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 450, 22));

    jLabel8.setBackground(new java.awt.Color(204, 204, 204));
    jLabel8.setText("Teléfono: 2212222245");
    jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 209, 22));

    jLabel10.setBackground(new java.awt.Color(204, 204, 204));
    jLabel10.setText("CP: 910000");
    jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 220, 22));

    jLabel11.setBackground(new java.awt.Color(204, 204, 204));
    jLabel11.setText("Dirección: José Azueta #124");
    jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 209, 22));

    jLabel13.setBackground(new java.awt.Color(204, 204, 204));
    jLabel13.setText("Carrera: Ingeniería de Software");
    jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 220, 22));

    jLabel14.setBackground(new java.awt.Color(204, 204, 204));
    jLabel14.setText("Facultad: Estadística e Informática");
    jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 220, 22));

    jLabel15.setBackground(new java.awt.Color(204, 204, 204));
    jLabel15.setText("Telefono (opcional):");
    jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 150, 22));

    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/2-user_-_single_add-128.png"))); // NOI18N
    jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

    jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    jLabel17.setText("ID: zS1401643 ");
    jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

    txtSearchbar1.setText("22-33-44-55-33");
    txtSearchbar1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtSearchbar1ActionPerformed(evt);
      }
    });
    jPanel1.add(txtSearchbar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 189, -1));

    jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    jButton2.setText("Aceptar");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, -1));

    jLabel12.setBackground(new java.awt.Color(204, 204, 204));
    jLabel12.setText("Correo: nievejohn@aol.com");
    jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 209, 22));

    jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator4.setForeground(new java.awt.Color(51, 51, 51));
    jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 766, -1));

    txtSearchbar2.setText("Búsqueda...");
    txtSearchbar2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtSearchbar2ActionPerformed(evt);
      }
    });
    jPanel1.add(txtSearchbar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, -1));

    jButton3.setText("Ir");
    jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 53, -1));

    jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
    jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 766, -1));

    gestionUsuario2.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    gestionUsuario2.setText("Gestionar préstamo");
    gestionUsuario2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gestionUsuario2ActionPerformed(evt);
      }
    });
    jPanel1.add(gestionUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, 26));

    gestionUsuario1.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    gestionUsuario1.setText("Gestionar usuario");
    gestionUsuario1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gestionUsuario1ActionPerformed(evt);
      }
    });
    jPanel1.add(gestionUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, 26));

    gestionUsuario3.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    gestionUsuario3.setText("Verificar adeudo");
    gestionUsuario3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gestionUsuario3ActionPerformed(evt);
      }
    });
    jPanel1.add(gestionUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, 26));

    jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemabibliotecario/toolbar_home.png"))); // NOI18N
    jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, -1, 26));

    jPanel2.setBackground(new java.awt.Color(255, 255, 255));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1.png"))); // NOI18N
    jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

    jLabel3.setText("Facultad de Estadística e Informática, Universidad Veracruzana");
    jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

    lblTitle1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
    lblTitle1.setForeground(new java.awt.Color(0, 0, 102));
    lblTitle1.setText(" Sistema Bibliotecario \"BUAEEI\"");
    jPanel2.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 58));

    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uv1.png"))); // NOI18N
    jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 102, -1));

    jLabel16.setBackground(new java.awt.Color(204, 204, 204));
    jLabel16.setText("Titulo: introduccion a la programacion c++");
    jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 550, 22));

    jLabel18.setBackground(new java.awt.Color(204, 204, 204));
    jLabel18.setText("Número de folio: 111342412614");
    jLabel18.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 209, 22));

    jLabel19.setBackground(new java.awt.Color(204, 204, 204));
    jLabel19.setText("Fecha de prestamo: 04/05/2016");
    jLabel19.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 220, 22));

    jLabel21.setBackground(new java.awt.Color(204, 204, 204));
    jLabel21.setText("Tipo:");
    jLabel21.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 50, 22));

    jLabel22.setBackground(new java.awt.Color(204, 204, 204));
    jLabel22.setText("ID usuario lector: zS14011543");
    jLabel22.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 220, 22));

    jLabel23.setBackground(new java.awt.Color(204, 204, 204));
    jLabel23.setText("Nombre: Jose Manuel Lopez");
    jLabel23.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 220, 22));

    jLabel24.setBackground(new java.awt.Color(204, 204, 204));
    jLabel24.setText("Fecha de devolucion: 10/05/2016");
    jLabel24.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 280, 22));

    btnAceptar.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    btnAceptar.setText("Aceptar");
    btnAceptar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAceptarActionPerformed(evt);
      }
    });
    jPanel2.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

    jLabel27.setBackground(new java.awt.Color(204, 204, 204));
    jLabel27.setText("Editorial: Norma");
    jLabel27.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
    jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 209, 22));

    jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator6.setForeground(new java.awt.Color(51, 51, 51));
    jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 766, 10));

    txtSearchbar4.setText("Búsqueda...");
    txtSearchbar4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtSearchbar4ActionPerformed(evt);
      }
    });
    jPanel2.add(txtSearchbar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, -1));

    jButton5.setText("Ir");
    jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 53, -1));

    jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator7.setForeground(new java.awt.Color(51, 51, 51));
    jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 766, -1));

    btnGestionarPrestamo.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    btnGestionarPrestamo.setText("Gestionar préstamo");
    btnGestionarPrestamo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGestionarPrestamoActionPerformed(evt);
      }
    });
    jPanel2.add(btnGestionarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, 26));

    btnGestionarUsuario.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    btnGestionarUsuario.setText("Gestionar usuario");
    btnGestionarUsuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGestionarUsuarioActionPerformed(evt);
      }
    });
    jPanel2.add(btnGestionarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, 26));

    gestionUsuario6.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
    gestionUsuario6.setText("Verificar adeudo");
    gestionUsuario6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        gestionUsuario6ActionPerformed(evt);
      }
    });
    jPanel2.add(gestionUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, 26));

    jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_home_black_24dp_1x.png"))); // NOI18N
    jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, 26));

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libro", "Revista", "Tesis", "Item 4" }));
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox1ActionPerformed(evt);
      }
    });
    jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 140, 20));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 750, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void txtSearchbar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchbar1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtSearchbar1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton2ActionPerformed

  private void txtSearchbar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchbar2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtSearchbar2ActionPerformed

  private void gestionUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuario2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_gestionUsuario2ActionPerformed

  private void gestionUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuario1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_gestionUsuario1ActionPerformed

  private void gestionUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuario3ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_gestionUsuario3ActionPerformed

  private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnAceptarActionPerformed

  private void txtSearchbar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchbar4ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtSearchbar4ActionPerformed

  private void btnGestionarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarPrestamoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnGestionarPrestamoActionPerformed

  private void btnGestionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarUsuarioActionPerformed
      MenuUsuario mu = new MenuUsuario();
      mu.setVisible(true);    // TODO add your handling code here:
  }//GEN-LAST:event_btnGestionarUsuarioActionPerformed

  private void gestionUsuario6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionUsuario6ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_gestionUsuario6ActionPerformed

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jComboBox1ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAceptar;
  private javax.swing.JButton btnGestionarPrestamo;
  private javax.swing.JButton btnGestionarUsuario;
  private javax.swing.JButton gestionUsuario1;
  private javax.swing.JButton gestionUsuario2;
  private javax.swing.JButton gestionUsuario3;
  private javax.swing.JButton gestionUsuario6;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton5;
  private javax.swing.JComboBox<String> jComboBox1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel20;
  private javax.swing.JLabel jLabel21;
  private javax.swing.JLabel jLabel22;
  private javax.swing.JLabel jLabel23;
  private javax.swing.JLabel jLabel24;
  private javax.swing.JLabel jLabel27;
  private javax.swing.JLabel jLabel28;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JSeparator jSeparator4;
  private javax.swing.JSeparator jSeparator5;
  private javax.swing.JSeparator jSeparator6;
  private javax.swing.JSeparator jSeparator7;
  private javax.swing.JLabel lblTitle;
  private javax.swing.JLabel lblTitle1;
  private javax.swing.JTextField txtSearchbar1;
  private javax.swing.JTextField txtSearchbar2;
  private javax.swing.JTextField txtSearchbar4;
  // End of variables declaration//GEN-END:variables
}
